### ISSUE TITLE
Can't start web API on Ubuntu 22.04

### ISSUE THREAD

**Issue by Robindeko** [JnyJny/busylight#135]
Thanks for this great project!
I can finally use the KUANDO Busylight on my Ubuntu install.

Unfortunately, both the Busylight library and the web API installed correctly (according to PIP), I can't start the Web API.
it keeps on saying "command not found", while the "busylight" command runs without issues.

Does anyone have any tips for me?
Thanks in advance.

**Comment by Robindeko** [comment]
Hi JnyJny,

Thank you very much for your quick reply.
It simply says, busyserve: command not found.

![image](https://user-images.githubusercontent.com/74138988/167928872-bb623de0-5502-4930-953b-6a6a9acb625b.png)

**Comment by JnyJny** [comment]
So maybe we should back up. How did you install `busylight-for-humans` and what version is it?

```console
$ python3 -m pip install 'busylight-for-humans[webapi]'
$ python3 -m pip list | grep busy
busylight-for-humans 0.17.2
```
Depending on your shell, the square brackets can cause problems in how the command is interpreted by the shell. Putting them inside the single quotes should keep the shell interpreting them differently then we intended.  For versions 0.16 and earlier, the webapi was started using a subcommand of `busylight`, namely `busylight serve`. For versions 0.17 and later, it's a second command `busyserve`.

**Comment by JnyJny** [comment]
Hey! It's a bug in my `pyproject.toml` file, probably from when I merged the master and asyncio branches.

Should have a fix for it pretty quick.

**Comment by Robindeko** [comment]
Thanks, good to hear it's probably a bug :)
By the way, when I grep the installed modules from pip, only the busylight-for-humans shows up.

**Comment by JnyJny** [comment]
Fixed the pyproject.toml with 09822c2

**Comment by JnyJny** [comment]
Ok, version 0.17.3 on pypi should install `busylight` and `busyserve` as expected when installed with the `[webapi]` extras.

**Comment by Robindeko** [comment]
awesome, thanks!
I had to run `python3 -m pip install -U busylight-for-humans` to update it to 0.17.3
Works like a charm now.
Thanks again!
