### ISSUE TITLE
Class and file conventions

### ISSUE THREAD

**Issue by henryruhs** [JnyJny/busylight#193]
1. the status indicator does not follow the class convention.

`busylight.lights.plantronics import status_indicator` should be `Status_Indicator`

2. the fit statusb does not follow the file convention

`fit_statUSB.py` should be `fit_statusb.py`

* conventions are extracted from the codebase

**Comment by JnyJny** [comment]
Pull request?

**Comment by JnyJny** [comment]
Also I can't find any instances of `busylight.lights.plantronics import status_indicator` in the code base.

**Comment by henryruhs** [comment]
I was wrong (properly need so sleep), there is indeed `Status_Indicator`.
