### ISSUE TITLE
LightNotFound has been removed

### ISSUE THREAD

**Issue by henryruhs** [JnyJny/busylight#230]
Just a clearification, I figured out that `LightNotFound` has been replaced by `NoLightsFound`? Is it save to search and replace it?

This [entry](https://github.com/JnyJny/busylight/blob/master/busylight/lights/__init__.py#L79) in `__all__` could be removed then. Kind of tricky as my IDE could not warn me of that undeclared class.

**Comment by JnyJny** [comment]
Thank you, the `LightNotFound` exeception was removed but I missed removing it from the `__all__` list in the lights module.

**Comment by JnyJny** [comment]
Version 0.25.4 on PyPi
