### ISSUE TITLE
Support for Sennheiser Busylight

### ISSUE THREAD

**Issue by redaxmedia** [JnyJny/busylight#27]
Sennheiser has another light that could be added to this library.

https://www.youtube.com/watch?v=B7D7DkVItKI

**Comment by JnyJny** [comment]
There is a surprising lack of information about this piece of hardware. Guess I'll have to order one and snoop it to find out how it works.

**Comment by redaxmedia** [comment]
@JnyJny Get in touch with the support - I made good experiences asking Luxaflor and Kuando for free examples.

**Comment by JnyJny** [comment]
It would seem this light has been discontinued by the manufacturer. I've found it for sale in Europe and Australia, shipping to the US would have doubled the price of the light. Unless someone loans me one it's unlikely this will ever get supported.
