### ISSUE TITLE
[QUESTION] High lumen / lux for daylight visibility

### ISSUE THREAD

**Issue by jrecasens** [JnyJny/busylight#337]
I recently acquired a BlinkStick Square and a ThingM Blink(1), and they've been performing excellently with the busylight package. However, I've encountered an issue: neither device is visible in direct sunlight during the day.

Does anyone have suggestions for a solution or an alternative product that could address this visibility issue in daylight?

Thanks, Javier

**Comment by JnyJny** [comment]
Hi Javier, unfortunately I don't have any hard data about device luminosity. Looking at all the supported devices on hand, they all have some sort of translucent diffuser to smooth out LED source hot spots, decreasing their output but producing a more even lighting effect. Removing the diffuser from my BlinkStick Square reveals eight of the large multi-color LEDs which are pretty harsh when lit but should be more visible in direct daylight. Some of the lights have dim/normal settings (BlyncLight family) but still only have 255 intensity steps per color channel (same as all the other lights). The fit-StatUSB light is the smallest light I am aware of and has the clearest diffuser, but it only has one small LED.

Lights with easily removable diffusers:
- BusyLight
- BusyLight Plus
- BlinkStick Square

You could reach out to the BlinkStick or ThingM folks to see if they have any thoughts about daylight visible devices (@todbot)

You might also consider LED products found at [Ada Fruit](adafruit.com) or [Spark Fun](sparkfun.com) but you'll likely need to be comfortable with a little soldering and firmware style programming to get a device similar to the commercial examples.

Sorry I don't have better options for you :( I'm curious to see where your quest takes you.

**Comment by JnyJny** [comment]
Now I am curious about your application and design constraints!  I took a quick look at the K50 family of products, and I'm encouraged by the beacon version. While not being the top-performer WRT lumens per color, I like that the light is upward firing into a reflector which enhances directionality. If your power envelope is forgiving enough, that may be a "close enough" solution.  Looking at more of the Banner Engineering products, the K90 daylight series lights are interesting but seem to lack the programmability of the K50 series.

I'm sorry I haven't been very helpful, but it is very interesting to hear about the types of problems people are trying to solve with BusyLight.
