### ISSUE TITLE
[BUG] typer 0.12.3 seems to work despite the requirements for a typer <0.10

### ISSUE THREAD

**Issue by NGeorgescu** [JnyJny/busylight#347]
not having the most up to date `typer` package has a conflict with  some other packages that I use.  Not sure how important the <0.10  requirement is (which installs 0.9.4)

seems to work just fine on my system for the functionality of  busylight `on` and `rainbow`.

Thanks.

**Comment by JnyJny** [comment]
Thanks for the prod, I've updated the dependencies in pyproject to accept the latest version of typer.  Let me know if that fixes the problem you ran into.

**Comment by JnyJny** [comment]
Of course I found some other deps that were out of date,  just published version 0.30.0 with the updated dependencies.
