### ISSUE TITLE
Wrong naming Agile Innovative

### ISSUE THREAD

**Issue by redaxmedia** [JnyJny/busylight#40]
Hello,

for some reason you used "Innovations" over "Innovative" and therefore the code and docs have incorrect naming.

**Comment by JnyJny** [comment]
Passive aggressive issues opened over spelling errors (whose location was not identified) would be better served with pull requests correcting the perceived problems.

**Comment by redaxmedia** [comment]
Erik, I think you got me wrong here. This issue wasn't meant to be "passive aggressive" ... I just wanted to correct the namespace of the classes in the right way - better to be fixed now than later.

That being said: a pull request has been send and I hope you won't act that offended in the future as I like your library and just want to contribute to it.

**Comment by JnyJny** [comment]
Please consider reading this: https://snarky.ca/the-social-contract-of-open-source/

**Comment by redaxmedia** [comment]
This is a very negative statement about OpenSource... I suggest you get in touch with me on Discord, Telegram or whatever and we talk while enjoying a beer
