### ISSUE TITLE
Suggestions for the Web API

### ISSUE THREAD

**Issue by redaxmedia** [JnyJny/busylight#41]
1. Developers usually open `/` of the API initially - therefore a `{"detail":"Not Found"}` is not helpful. It would be nice to have a href index of all endpoints instead
1. Rename `detail | "Not Found"` to `message | "Not Found"`
1. There might be a technical reason but please try to get rid of the `/1/` inside the API routing
1. Improve HTTP status codes... an empty `/lights` should properly not return 200 Ok but an 204 No Content

**Comment by JnyJny** [comment]
I am more than happy to accept pull request to address these short comings in the web API.

**Comment by redaxmedia** [comment]
@JnyJny Here we go: https://github.com/JnyJny/busylight/pull/43
