### ISSUE TITLE
Not able to install the webapi version

### ISSUE THREAD

**Issue by alexander-paterson** [JnyJny/busylight#60]
If I run `python3 -m pip install busylight-for-humans[webapi]` I get the following response: `no matches found: busylight-for-humans[webapi]`

Can I just install uvicorn and FastAPI manually?

**Comment by JnyJny** [comment]
My guess is you are using a shell that interprets the text between the square braces as a regular expression character class (csh derivatives do that), thus the "no matches found" error message.

Try:
```console
$ python3 -m pip install "busylight-for-humans[webapi]"
```

**Comment by alexander-paterson** [comment]
Thanks, that fixed it. Maybe an idea to edit the readme to include the `""` around it or at least put a note under the command?
